Repository CA-G12/Ecommerce-App-Team-2, pull requests merged in 2022-07, with the labels that each got.

#12 2 file structure
  JS/app.js
  css/main.css
  html/home.html
  images/home.webp
  index.html
Labels: for-review

#13 create a readme file to describe how to use the website
  README.md
Labels: for-review

#30 4 create hero section
  css/index.css
  images/home.webp
  images/image-bg.webp
  images/logo.png
  index.html
Labels: awating-review

#31 create and style the product page
  css/productDetails.css
  html/productPage.html
  images/car1.jpg
Labels: for-review

#32 10 create add new product
  css/addNewProduct.css
  html/addNewProduct.html
Labels: for-review

#33 create edit product
  html/editProduct.html
Labels: for-review

#34 create and design seller page , i added a table and search input
  css/seller.css
  html/seller.html
  images/bmw.jpg
  images/search-icons.png
Labels: awating-review

#35 create and styling customer page by html and css
  css/customer.css
  html/customer.html
  images/car1.jpg
  images/cart-shopping-solid.svg
Labels: awating-review

#37 14 create search function
  JS/displayProductDetails/dom.js
  JS/displayProductDetails/logic.js
Labels: awating-review

#36 create display product function to dispaly product detials in the page
  JS/ProductDeitals/porductPage.js
  html/productPage.html
Labels: awating-review

#39 create a function to display all products from the local storage
  JS/seller/dom.js
  JS/seller/logic.js
  css/seller.css
  html/seller.html
Labels: awating-review

#41 create add to cart function and save product in the local storage
  JS/ProductDeitals/dom.js
  JS/ProductDeitals/logic.js
  JS/ProductDeitals/porductPage.js
  html/productPage.html
Labels: awating-review

#42 edit object names prop
  JS/ProductDeitals/logic.js
Labels: awating-review

#43 21 create display products function
  JS/displayAllProduct/logic.js
Labels: done

#46 create a function to filter all products in manage product page
  .gitignore
  JS/seller/dom.js
  JS/seller/logic.js
  JS/seller/test.test.js
  package-lock.json
  package.json
Labels: for-review
